name: Discord notification

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_RELEASE_WEBHOOK}}
          DISCORD_EMBEDS:
            '[{ "title":"${{github.event.head_commit.message}}", "footer":{"text":"Pushed by ${{github.event.head_commit.author.name}}"} }]'
        uses: Ilshidur/action-discord@0.3.2
