name: Notify Discord on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send test Discord message
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_RELEASE_WEBHOOK }}
        with:
          message: "✅ Test réussi depuis GitHub Actions"
